# Generated by Django 2.0.6 on 2018-07-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180710_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ad',
        ),
        migrations.AddField(
            model_name='blog',
            name='userinfo',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
            preserve_default=False,
        ),
    ]
