# Generated by Django 2.0.6 on 2018-07-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180711_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_count',
            field=models.IntegerField(default=0),
        ),
    ]
