# Generated by Django 2.0.6 on 2018-07-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180711_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tilte',
            new_name='title',
        ),
    ]
