# Generated by Django 2.0.6 on 2018-07-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180711_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aritalupdown',
            unique_together=set(),
        ),
    ]
