# Generated by Django 2.0.6 on 2018-07-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180712_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_count',
        ),
    ]
