# Generated by Django 2.0.6 on 2018-07-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_comment_content_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artical2tag',
            unique_together=set(),
        ),
    ]
