# Generated by Django 2.0.6 on 2018-07-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180715_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=255, verbose_name='评论内容'),
        ),
    ]
